In [2]:
import pandas as pd

In [3]:
f = './Data/pts_by_tab.xlsx'

In [4]:
df = pd.read_excel(f)
df

              Test  Test Result
0       Knicknacks     0.794170
1      Paddywhacks     0.967262
2         Dogbones     0.629260
3            Snips     0.983582
4           Snails     0.753707
5       PuppyTails     0.466446
6            Sugar     0.621030
7            Spice     0.926020
8   EverythingNice     0.874326
9         Furlongs     0.288406
10      Fortnights     0.135257
11      Cromulence     0.447925

In [7]:
# It complained that I didn't have this file so I installed it with:
# ! pip install openpyxl

In [5]:
pd.read_excel?

# Checking the docs revealed that there's a sheet_name parameter
#  Checking the details, it shows that explicitly using "sheet_name=None" imports
#  all of the sheets

Signature:
pd.read_excel(
    io,
    sheet_name: 'str | int | list[IntStrT] | None' = 0,
    *,
    header: 'int | Sequence[int] | None' = 0,
    names: 'list[str] | None' = None,
    index_col: 'int | Sequence[int] | None' = None,
    usecols: 'int | str | Sequence[int] | Sequence[str] | Callable[[str], bool] | None' = None,
    dtype: 'DtypeArg | None' = None,
    engine: "Literal['xlrd', 'openpyxl', 'odf', 'pyxlsb'] | None" = None,
    converters: 'dict[str, Callable] | dict[int, Callable] | None' = None,
    true_values: 'Iterable[Hashable] | None' = None,
    false_values: 'Iterable[Hashable] | None' = None,
    skiprows: 'Sequence[int] | int | Callable[[int], object] | None' = None,
    nrows: 'int | None' = None,
    na_values=None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool' = False,
    parse_dates: 'list | dict | bool' = False,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'dict[Hashable, str] | str | None' = None,
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    comment: 'str | None' = None,
    skipfooter: 'int' = 0,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
    engine_kwargs: 'dict | None' = None,
) -> 'DataFrame | dict[IntStrT, DataFrame]'
Docstring:
Read an Excel file into a pandas DataFrame.

Supports `xls`, `xlsx`, `xlsm`, `xlsb`, `odf`, `ods` and `odt` file extensions
read from a local filesystem or URL. Supports an option to read
a single sheet or a list of sheets.

Parameters
----------
io : str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, and file. For file URLs, a host is
    expected. A local file could be: ``file://localhost/path/to/table.xlsx``.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method,
    such as a file handle (e.g. via builtin ``open`` function)
    or ``StringIO``.

    .. deprecated:: 2.1.0
        Passing byte strings is deprecated. To read from a
        byte string, wrap it in a ``BytesIO`` object.
sheet_name : str, int, list, or None, default 0
    Strings are used for sheet names. Integers are used in zero-indexed
    sheet positions (chart sheets do not count as a sheet position).
    Lists of strings/integers are used to request multiple sheets.
    Specify None to get all worksheets.

    Available cases:

    * Defaults to ``0``: 1st sheet as a `DataFrame`
    * ``1``: 2nd sheet as a `DataFrame`
    * ``"Sheet1"``: Load sheet with name "Sheet1"
    * ``[0, 1, "Sheet5"]``: Load first, second and sheet named "Sheet5"
      as a dict of `DataFrame`
    * None: All worksheets.

header : int, list of int, default 0
    Row (0-indexed) to use for the column labels of the parsed
    DataFrame. If a list of integers is passed those row positions will
    be combined into a ``MultiIndex``. Use None if there is no header.
names : array-like, default None
    List of column names to use. If file contains no header row,
    then you should explicitly pass header=None.
index_col : int, str, list of int, default None
    Column (0-indexed) to use as the row labels of the DataFrame.
    Pass None if there is no such column.  If a list is passed,
    those columns will be combined into a ``MultiIndex``.  If a
    subset of data is selected with ``usecols``, index_col
    is based on the subset.

    Missing values will be forward filled to allow roundtripping with
    ``to_excel`` for ``merged_cells=True``. To avoid forward filling the
    missing values use ``set_index`` after reading the data instead of
    ``index_col``.
usecols : str, list-like, or callable, default None
    * If None, then parse all columns.
    * If str, then indicates comma separated list of Excel column letters
      and column ranges (e.g. "A:E" or "A,C,E:F"). Ranges are inclusive of
      both sides.
    * If list of int, then indicates list of column numbers to be parsed
      (0-indexed).
    * If list of string, then indicates list of column names to be parsed.
    * If callable, then evaluate each column name against it and parse the
      column if the callable returns ``True``.

    Returns a subset of the columns according to behavior above.
dtype : Type name or dict of column -> type, default None
    Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
    Use `object` to preserve data as stored in Excel and not interpret dtype.
    If converters are specified, they will be applied INSTEAD
    of dtype conversion.
engine : str, default None
    If io is not a buffer or path, this must be set to identify io.
    Supported engines: "xlrd", "openpyxl", "odf", "pyxlsb".
    Engine compatibility :

    - "xlrd" supports old-style Excel files (.xls).
    - "openpyxl" supports newer Excel file formats.
    - "odf" supports OpenDocument file formats (.odf, .ods, .odt).
    - "pyxlsb" supports Binary Excel files.

    .. versionchanged:: 1.2.0
        The engine `xlrd <https://xlrd.readthedocs.io/en/latest/>`_
        now only supports old-style ``.xls`` files.
        When ``engine=None``, the following logic will be
        used to determine the engine:

       - If ``path_or_buffer`` is an OpenDocument format (.odf, .ods, .odt),
         then `odf <https://pypi.org/project/odfpy/>`_ will be used.
       - Otherwise if ``path_or_buffer`` is an xls format,
         ``xlrd`` will be used.
       - Otherwise if ``path_or_buffer`` is in xlsb format,
         ``pyxlsb`` will be used.

         .. versionadded:: 1.3.0
       - Otherwise ``openpyxl`` will be used.

         .. versionchanged:: 1.3.0

converters : dict, default None
    Dict of functions for converting values in certain columns. Keys can
    either be integers or column labels, values are functions that take one
    input argument, the Excel cell content, and return the transformed
    content.
true_values : list, default None
    Values to consider as True.
false_values : list, default None
    Values to consider as False.
skiprows : list-like, int, or callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (int) at the
    start of the file. If callable, the callable function will be evaluated
    against the row indices, returning True if the row should be skipped and
    False otherwise. An example of a valid callable argument would be ``lambda
    x: x in [0, 2]``.
nrows : int, default None
    Number of rows to parse.
na_values : scalar, str, list-like, or dict, default None
    Additional strings to recognize as NA/NaN. If dict passed, specific
    per-column NA values. By default the following values are interpreted
    as NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
    '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'None',
    'n/a', 'nan', 'null'.
keep_default_na : bool, default True
    Whether or not to include the default NaN values when parsing the data.
    Depending on whether `na_values` is passed in, the behavior is as follows:

    * If `keep_default_na` is True, and `na_values` are specified, `na_values`
      is appended to the default NaN values used for parsing.
    * If `keep_default_na` is True, and `na_values` are not specified, only
      the default NaN values are used for parsing.
    * If `keep_default_na` is False, and `na_values` are specified, only
      the NaN values specified `na_values` are used for parsing.
    * If `keep_default_na` is False, and `na_values` are not specified, no
      strings will be parsed as NaN.

    Note that if `na_filter` is passed in as False, the `keep_default_na` and
    `na_values` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of na_values). In
    data without any NAs, passing na_filter=False can improve the performance
    of reading a large file.
verbose : bool, default False
    Indicate number of NA values placed in non-numeric columns.
parse_dates : bool, list-like, or dict, default False
    The behavior is as follows:

    * bool. If True -> try parsing the index.
    * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
      a single date column.
    * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
      result 'foo'

    If a column or index contains an unparsable date, the entire column or
    index will be returned unaltered as an object data type. If you don`t want to
    parse some cells as date just change their type in Excel to "Text".
    For non-standard datetime parsing, use ``pd.to_datetime`` after ``pd.read_excel``.

    Note: A fast-path exists for iso8601-formatted dates.
date_parser : function, optional
    Function to use for converting a sequence of string columns to an array of
    datetime instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. Pandas will try to call `date_parser` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by `parse_dates` into a single array
    and pass that; and 3) call `date_parser` once for each row using one or
    more strings (corresponding to the columns defined by `parse_dates`) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`to_datetime` as-needed.
date_format : str or dict of column -> format, default ``None``
   If used in conjunction with ``parse_dates``, will parse dates according to this
   format. For anything more complex,
   please read in as ``object`` and then apply :func:`to_datetime` as-needed.

   .. versionadded:: 2.0.0
thousands : str, default None
    Thousands separator for parsing string columns to numeric.  Note that
    this parameter is only necessary for columns stored as TEXT in Excel,
    any numeric columns will automatically be parsed, regardless of display
    format.
decimal : str, default '.'
    Character to recognize as decimal point for parsing string columns to numeric.
    Note that this parameter is only necessary for columns stored as TEXT in Excel,
    any numeric columns will automatically be parsed, regardless of display
    format.(e.g. use ',' for European data).

    .. versionadded:: 1.4.0

comment : str, default None
    Comments out remainder of line. Pass a character or characters to this
    argument to indicate comments in the input file. Any data between the
    comment string and the end of the current line is ignored.
skipfooter : int, default 0
    Rows at the end to skip (0-indexed).
storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

    .. versionadded:: 1.2.0

dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). Behaviour is as follows:

    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
      (default).
    * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
      DataFrame.

    .. versionadded:: 2.0

engine_kwargs : dict, optional
    Arbitrary keyword arguments passed to excel engine.

Returns
-------
DataFrame or dict of DataFrames
    DataFrame from the passed in Excel file. See notes in sheet_name
    argument for more information on when a dict of DataFrames is returned.

See Also
--------
DataFrame.to_excel : Write DataFrame to an Excel file.
DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_fwf : Read a table of fixed-width formatted lines into DataFrame.

Notes
-----
For specific information on the methods used for each Excel engine, refer to the pandas
:ref:`user guide <io.excel_reader>`

Examples
--------
The file can be read using the file name as string or an open file object:

>>> pd.read_excel('tmp.xlsx', index_col=0)  # doctest: +SKIP
       Name  Value
0   string1      1
1   string2      2
2  #Comment      3

>>> pd.read_excel(open('tmp.xlsx', 'rb'),
...               sheet_name='Sheet3')  # doctest: +SKIP
   Unnamed: 0      Name  Value
0           0   string1      1
1           1   string2      2
2           2  #Comment      3

Index and header can be specified via the `index_col` and `header` arguments

>>> pd.read_excel('tmp.xlsx', index_col=None, header=None)  # doctest: +SKIP
     0         1      2
0  NaN      Name  Value
1  0.0   string1      1
2  1.0   string2      2
3  2.0  #Comment      3

Column types are inferred but can be explicitly specified

>>> pd.read_excel('tmp.xlsx', index_col=0,
...               dtype={'Name': str, 'Value': float})  # doctest: +SKIP
       Name  Value
0   string1    1.0
1   string2    2.0
2  #Comment    3.0

True, False, and NA values, and thousands separators have defaults,
but can be explicitly specified, too. Supply the values you would like
as strings or lists of strings!

>>> pd.read_excel('tmp.xlsx', index_col=0,
...               na_values=['string1', 'string2'])  # doctest: +SKIP
       Name  Value
0       NaN      1
1       NaN      2
2  #Comment      3

Comment lines in the excel input file can be skipped using the `comment` kwarg

>>> pd.read_excel('tmp.xlsx', index_col=0, comment='#')  # doctest: +SKIP
      Name  Value
0  string1    1.0
1  string2    2.0
2     None    NaN
File:      ~/Library/Python/3.9/lib/python/site-packages/pandas/io/excel/_base.py
Type:      function

In [6]:
df_wb = pd.read_excel(f,sheet_name=None)

In [7]:
type(df_wb), type(df_wb['Subj1'])

(dict, pandas.core.frame.DataFrame)

In [8]:
# The problem as you described it would have a single data frame 
# and that data frame would have a subject column which matches the key for the 
# dictionary
#
# One way to do this would be to loop through the df_wb dictionary and add the column
# you want, then at the end, merge them all together

allsheets = []
for this_sheet in df_wb.items():
    this_subj_id = this_sheet[0]
    this_subj_data = this_sheet[1]
    
    this_subj_data['SubjID'] = this_subj_id # Make a new column with every entry as the subj ID
    allsheets.append(this_subj_data)

In [21]:
print(allsheets) # a list with a separate dataframe for each patient

[              Test  Test Result SubjID
0       Knicknacks     0.794170  Subj1
1      Paddywhacks     0.967262  Subj1
2         Dogbones     0.629260  Subj1
3            Snips     0.983582  Subj1
4           Snails     0.753707  Subj1
5       PuppyTails     0.466446  Subj1
6            Sugar     0.621030  Subj1
7            Spice     0.926020  Subj1
8   EverythingNice     0.874326  Subj1
9         Furlongs     0.288406  Subj1
10      Fortnights     0.135257  Subj1
11      Cromulence     0.447925  Subj1,               Test  Test Result SubjID
0       Knicknacks     0.061385  Subj2
1      Paddywhacks     0.342433  Subj2
2         Dogbones     0.103762  Subj2
3            Snips     0.500961  Subj2
4           Snails     0.270232  Subj2
5       PuppyTails     0.302421  Subj2
6            Sugar     0.869754  Subj2
7            Spice     0.592847  Subj2
8   EverythingNice     0.251587  Subj2
9         Furlongs     0.680921  Subj2
10      Fortnights     0.593490  Subj2
11      Cromulence     0.619362  Subj2,               Test  Test Result SubjID
0       Knicknacks     0.736560  Subj3
1      Paddywhacks     0.784149  Subj3
2         Dogbones     0.971409  Subj3
3            Snips     0.767895  Subj3
4           Snails     0.540919  Subj3
5       PuppyTails     0.812076  Subj3
6            Sugar     0.547434  Subj3
7            Spice     0.029197  Subj3
8   EverythingNice     0.066690  Subj3
9         Furlongs     0.957161  Subj3
10      Fortnights     0.816897  Subj3
11      Cromulence     0.617761  Subj3]

In [9]:
df = pd.concat(allsheets)
df

              Test  Test Result SubjID
0       Knicknacks     0.794170  Subj1
1      Paddywhacks     0.967262  Subj1
2         Dogbones     0.629260  Subj1
3            Snips     0.983582  Subj1
4           Snails     0.753707  Subj1
5       PuppyTails     0.466446  Subj1
6            Sugar     0.621030  Subj1
7            Spice     0.926020  Subj1
8   EverythingNice     0.874326  Subj1
9         Furlongs     0.288406  Subj1
10      Fortnights     0.135257  Subj1
11      Cromulence     0.447925  Subj1
0       Knicknacks     0.061385  Subj2
1      Paddywhacks     0.342433  Subj2
2         Dogbones     0.103762  Subj2
3            Snips     0.500961  Subj2
4           Snails     0.270232  Subj2
5       PuppyTails     0.302421  Subj2
6            Sugar     0.869754  Subj2
7            Spice     0.592847  Subj2
8   EverythingNice     0.251587  Subj2
9         Furlongs     0.680921  Subj2
10      Fortnights     0.593490  Subj2
11      Cromulence     0.619362  Subj2
0       Knicknacks     0.736560  Subj3
1      Paddywhacks     0.784149  Subj3
2         Dogbones     0.971409  Subj3
3            Snips     0.767895  Subj3
4           Snails     0.540919  Subj3
5       PuppyTails     0.812076  Subj3
6            Sugar     0.547434  Subj3
7            Spice     0.029197  Subj3
8   EverythingNice     0.066690  Subj3
9         Furlongs     0.957161  Subj3
10      Fortnights     0.816897  Subj3
11      Cromulence     0.617761  Subj3

In [11]:
# Consider organizing  data differently; each patient as a row, each column as a measure

In [12]:
df_p = pd.pivot(df, columns='Test', index='SubjID')

print('This is the natural way to store data for many kinds of statistcal analysis')
df_p

This is the natural way to store data for many kinds of statistcal analysis

       Test Result                                                           \
Test    Cromulence  Dogbones EverythingNice Fortnights  Furlongs Knicknacks
SubjID
Subj1     0.447925  0.629260       0.874326   0.135257  0.288406   0.794170
Subj2     0.619362  0.103762       0.251587   0.593490  0.680921   0.061385
Subj3     0.617761  0.971409       0.066690   0.816897  0.957161   0.736560


Test   Paddywhacks PuppyTails    Snails     Snips     Spice     Sugar
SubjID
Subj1     0.967262   0.466446  0.753707  0.983582  0.926020  0.621030
Subj2     0.342433   0.302421  0.270232  0.500961  0.592847  0.869754
Subj3     0.784149   0.812076  0.540919  0.767895  0.029197  0.547434

In [ ]:
# A slightly idfferent approach:
# Read it in as already-pivoted

In [24]:
df_wb = pd.read_excel(f,index_col=0,sheet_name=None)
allsheets=[]

for this_sheet in df_wb.items():
    this_subj_id = this_sheet[0]
    this_subj_data = this_sheet[1]
    
    this_subj_data = this_subj_data.T  # transpose
    this_subj_data.index = pd.Index([this_subj_id])
    allsheets.append(this_subj_data)

In [25]:
df = pd.concat(allsheets)
df

Test,Knicknacks,Paddywhacks,Dogbones,Snips,Snails,PuppyTails,Sugar,Spice,EverythingNice,Furlongs,Fortnights,Cromulence
Subj1,0.794170,0.967262,0.629260,0.983582,0.753707,0.466446,0.621030,0.926020,0.874326,0.288406,0.135257,0.447925
Subj2,0.061385,0.342433,0.103762,0.500961,0.270232,0.302421,0.869754,0.592847,0.251587,0.680921,0.593490,0.619362
Subj3,0.736560,0.784149,0.971409,0.767895,0.540919,0.812076,0.547434,0.029197,0.066690,0.957161,0.816897,0.617761