In [ ]:
##########################################################################################
#                                                                                        #
#  888888b.  8888888 .d88888b.   .d8888b.     .d8888b.   .d8888b.      d8888      d8888  #
#  888  "88b   888  d88P" "Y88b d88P  Y88b   d88P  Y88b d88P  Y88b    d8P888     d8P888  #
#  888  .88P   888  888     888 Y88b.        888        888          d8P 888    d8P 888  #
#  8888888K.   888  888     888  "Y888b.     888d888b.  888d888b.   d8P  888   d8P  888  #
#  888  "Y88b  888  888     888     "Y88b.   888P "Y88b 888P "Y88b d88   888  d88   888  #
#  888    888  888  888     888       "888   888    888 888    888 8888888888 8888888888 #
#  888   d88P  888  Y88b. .d88P Y88b  d88P   Y88b  d88P Y88b  d88P       888        888  #
#  8888888P" 8888888 "Y88888P"   "Y8888P"     "Y8888P"   "Y8888P"        888        888  #
#                                                                                        # 
##########################################################################################
#
# CSV Metabolomics Data Wrangling
#
##########################################################################################

In [ ]:
##########################################################################################
#                                                                                        #
#  888888b.  8888888 .d88888b.   .d8888b.     .d8888b.   .d8888b.      d8888      d8888  #
#  888  "88b   888  d88P" "Y88b d88P  Y88b   d88P  Y88b d88P  Y88b    d8P888     d8P888  #
#  888  .88P   888  888     888 Y88b.        888        888          d8P 888    d8P 888  #
#  8888888K.   888  888     888  "Y888b.     888d888b.  888d888b.   d8P  888   d8P  888  #
#  888  "Y88b  888  888     888     "Y88b.   888P "Y88b 888P "Y88b d88   888  d88   888  #
#  888    888  888  888     888       "888   888    888 888    888 8888888888 8888888888 #
#  888   d88P  888  Y88b. .d88P Y88b  d88P   Y88b  d88P Y88b  d88P       888        888  #
#  8888888P" 8888888 "Y88888P"   "Y8888P"     "Y8888P"   "Y8888P"        888        888  #
#                                                                                        # 
##########################################################################################
#
# Slicing and Parsing
#
##########################################################################################

In [ ]:
##################################################################################################################
#
# YouDo:
#    1) Make a copy of this notebook with your name as a suffix:  
#       BIOS6644_CSV_Sugar_Metabolomics_FirstLast.ipynb
#    2) Do all work in this new notebook.
#    3) Place completed work in students/Module_1/Your_Name/
#    4) Push to your branch on GitHub to submit
#
##################################################################################################################

# Wrangling Sugar Metabolomics Data

In [1]:

import pandas as pd
import pylab as plt
import numpy as np
%matplotlib notebook

In [ ]:


# General info here:
#   https://data.mendeley.com/datasets/9z7ncwvxnz/1
#
# Data here:
#   https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/9z7ncwvxnz-1.zip

# I renamed mine to "sugar_metabolomics.csv" so I could remember what it is
data = '../Data/sugar_metabolomics.csv'

In [2]:
pwd

'C:\\Users\\austi\\Documents\\csph\\bios6644\\BIOS6644_Github\\BIOS6644_Spring_2024\\students\\austin_albino'

In [15]:
##################################################################################################################
#
# YouDo:
# 
#    1) Read the csv into a dataframe called df
#######################################  BEGIN STUDENT CODE  #####################################################

# 1) 
df = pd.read_csv('C:\\Users\\austi\\Documents\\csph\\bios6644\\BIOS6644_Github\\BIOS6644_Spring_2024\\students\\austin_albino\\data\\sugar_metabolomics.csv')
#######################################   END STUDENT CODE   #####################################################


df

,Unnamed: 0,Label,HMDB59655,HMDB00536,HMDB00161,HMDB00462,HMDB03911,HMDB00517,HMDB00168,HMDB00191,...,HMDB00251,HMDB00167,HMDB00906,HMDB00925,HMDB00929,HMDB00158,HMDB00289,HMDB00296,HMDB00883,HMDB00292
0,S1T1,1,0.352612,0.494408,0.633644,0.709561,0.178925,0.292374,0.636341,0.206757,...,1.367522,0.427678,0.881105,1.818773,0.376078,0.457591,0.693919,0.518379,0.559305,0.828004
1,S2T1,1,0.253429,0.370364,0.573543,0.878630,0.172076,0.371784,0.854985,0.243091,...,1.414836,0.560914,0.874912,1.247760,0.553144,0.616780,0.718227,0.878867,0.573256,0.969989
2,S3T1,1,0.312914,0.387282,0.650851,0.725221,0.158010,0.367671,0.830597,0.216258,...,1.254878,0.549462,0.753802,1.591287,0.637100,0.849958,0.717387,0.754120,0.596909,0.854193
3,S4T1,1,0.453477,0.724525,0.643200,0.848350,0.201028,0.332246,0.663121,0.366776,...,1.728605,0.523544,0.712971,1.247983,0.568837,0.692736,0.684906,1.083854,0.805366,0.821716
4,S5T1,1,0.279043,0.578734,0.466216,0.763499,0.243987,0.381840,0.642630,0.251655,...,1.500024,0.465570,0.651820,1.495276,0.497882,0.523470,0.680014,0.800735,0.474378,0.943483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S83T2,2,0.336171,0.137917,0.500930,0.525551,0.058421,0.218825,0.453497,0.081870,...,0.811525,0.491936,0.736166,0.693040,0.511812,0.379706,0.516803,0.490038,0.471297,0.849468
116,S84T2,2,0.471108,0.071363,0.572382,0.420907,0.072989,0.241268,0.670890,0.071155,...,0.625635,0.477853,0.824301,0.615604,0.561920,0.635529,0.640501,0.706273,0.494590,0.781914
117,S85T2,2,0.398176,0.127460,0.563063,0.508767,0.083738,0.210915,0.510560,0.082728,...,0.741315,0.389742,0.886563,2.572234,0.438401,0.437176,0.680263,0.808022,0.473683,0.803452
118,S86T2,2,0.252117,0.182385,0.467339,0.325573,0.101329,0.272090,0.617825,0.093993,...,0.876985,0.448097,0.674240,0.665327,0.509795,0.455278,0.642249,0.527898,0.438984,0.959742
119,S87T2,2,0.384741,0.126316,0.502701,0.605335,0.094478,0.203800,0.570765,0.051917,...,0.825477,0.472086,0.853483,0.795963,0.527413,0.521801,0.823909,0.406853,0.470011,1.034818

In [28]:
##################################################################################################################
#
# YouDo:
# 
#    1) Notice that the import is wonky -- examine the data set
#       manually and figure out how to make it import cleanly.
#      
#       Ensure your data frame has the following handled correctly
#         a) the column names (1st row of the csv)
#.        b) The unlabeled first column is read as an index
#         c) The final row is totally weird--don't import it
#
#       (hint: pd.read_csv? lists various import options)
#
#######################################  BEGIN STUDENT CODE  #####################################################

# 1)
df = pd.read_csv('C:\\Users\\austi\\Documents\\csph\\bios6644\\BIOS6644_Github\\BIOS6644_Spring_2024\\students\\austin_albino\\data\\sugar_metabolomics.csv',index_col=0,engine='python',skipfooter=1)

#df.Label.value_counts()
#df.tail()
df.shape
#######################################   END STUDENT CODE   #####################################################
# assert df.shape == (92, 132)

(119, 74)

In [ ]:
##################################################################################################################
#
# YouDo:
# 
#    1) Get rid of any columns that have only NaN values
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html
#
#######################################  BEGIN STUDENT CODE  #####################################################



#######################################   END STUDENT CODE   #####################################################

assert df.shape == (92, 125)

In [ ]:
##################################################################################################################
#
# YouDo:
# 
#    1) Generate boxplots of Tryptophan levels separated based on 
#        the "Label" value
#
#      Use whatever plotting library you like.   
#      Hint 1: matplotlib has a boxplot tool
#          help(plt.boxplot)
#      Hint 2: pandas data frames have a built-in boxplot tool
#          help(df.boxplot)
#
#######################################  BEGIN STUDENT CODE  #####################################################


#######################################   END STUDENT CODE   #####################################################

In [ ]:
##################################################################################################################
#
# YouDo:
# Make a pair of plots as follows:
#    1) Show the correlation matrix between columns of the data
#        (hint 1: it should be 124x124, hint 2: check out plt.imshow() 
#         Hint 2: numpy has a function for generating the correlation matrix)
#
#    2) Make a similar plot showing correlation > 90%
#
#  Stretch goal:  using plt.subplot()  make a single figure with both plots side-by-side
#
#######################################  BEGIN STUDENT CODE  #####################################################



#######################################   END STUDENT CODE   #####################################################

In [ ]:
##################################################################################################################
#
# YouDo:
#  1) Remove any rows with na values
# 
#  2) Split the data into "test" and "train" bits with ~30% in the test set.
#       The "Label" column is the "y" data.  All other columns are the "X" data
#       Give them these names:
#       X_train, X_test, y_train, y_test

#######################################  BEGIN STUDENT CODE  #####################################################

# 1)


 
#2)

#######################################   END STUDENT CODE   #####################################################

In [ ]:
#Build a model to classify the Label based on the other columns

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=8675309)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=8675309,
                       verbose=0, warm_start=False)

In [ ]:
# Test the model
predictions = clf.predict(X_test)
reality = y_test

In [ ]:
# YouDo:
#  1) Evaluate the "goodness" of the predictions and write a paragraph describing the results as a markdown.
#
#######################################  BEGIN STUDENT CODE  #####################################################


#######################################   END STUDENT CODE   #####################################################

0.8125

# Analysis
It goes here.